In [29]:
import pandas as pd
from sklearn.datasets import fetch_california_housing

# Load the housing dataset
housing = fetch_california_housing()

X = pd.DataFrame(housing.data, columns=housing.feature_names) 
y = pd.Series(housing.target, name='med_house_value')

In [30]:
# Display the first five rows of the dataset
X.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

Features explained from https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset (Note to myself).

The target variable is the median house value for California districts, expressed in hundreds of thousands of dollars ($100,000).

MedInc - median income in block group.
HouseAge - median house age in block group.
AveRooms - average number of rooms per household.
AveBedrms - average number of bedrooms per household.
Population - block group population.
AveOccup - average number of household members.
Latitude - block group latitude.
Longitude - block group longitude.

In [31]:
# Print the feature names and check for missing values
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB

In [32]:
# Generate summary statistics (mean, min, max, etc.)
X.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000

In [33]:
from sklearn.model_selection import train_test_split

# Split the dataset into training and test sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                   random_state=42,
                                                   test_size=0.2)

# Train a linear regression model on the unscaled data using sklearn.linear_model.LinearRegression
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

# Make predictions on the test set
y_pred = lin_reg.predict(X_test)

In [34]:
# Evaluate model performance using MSE, RMSE, R^2
from sklearn.metrics import mean_squared_error, root_mean_squared_error, r2_score

# Evaluate model performance
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

print("Unscaled Data Model:")
print(f"Mean Squared Error: {mse:.2f}")
# On average the model fits within two points of predicting
print(f"Root Squared Error: {rmse:.2f}")
print(f"R² Score: {r2:.2f}")

Unscaled Data Model:
Mean Squared Error: 0.56
Root Squared Error: 0.75
R² Score: 0.58

In [35]:
print(pd.Series(lin_reg.coef_,
                index=X.columns))

MedInc        0.448675
HouseAge      0.009724
AveRooms     -0.123323
AveBedrms     0.783145
Population   -0.000002
AveOccup     -0.003526
Latitude     -0.419792
Longitude    -0.433708
dtype: float64

The R^2 tells us that about 58% of the variance in our dependent variable can be explained using our model. The model is capturing more than half of what we want it to but failing to pickup on a large portion of the data. The average number bedrooms feature has the largest impact on the outcome variable. For a 1 unit increase in average number of bedrooms the median house value for Californian districts increases by roughly 0.78. The Longitude and Latituted have the largest negative impact on the predictions. A 1 unit increase in longitude decreases the median house value by roughly 0.43. The root squared error tells us that predictions are off by about 0.75 units on average.

In [41]:
# Select three features from the dataset to build a simplified model. Explain your choice. (10 pts)


X = pd.DataFrame(housing.data, columns=housing.feature_names)

# Now select 3 features
X_select = X[['MedInc', 'AveBedrms', 'AveRooms']]

y_select = pd.Series(housing.target, name='med_house_value')

Explanation: I selected the median income column, the average bedrooms column, and the average rooms column because they had the larges coefficient weights in the previous model excluding the location data. So, I figured that these columns would provide better insights without the added noise from the other columns.

In [42]:
X_select_train, X_select_test, y_select_train, y_select_test = train_test_split(X_select, y_select,
                                                   random_state=42,
                                                   test_size=0.2)

# Train a linear regression model on the unscaled data using sklearn.linear_model.LinearRegression
from sklearn.linear_model import LinearRegression

lin_reg_select = LinearRegression()
lin_reg_select.fit(X_select_train, y_select_train)

# Make predictions on the test set
y_pred_select = lin_reg_select.predict(X_select_test)

In [43]:
# Evaluate model performance using MSE, RMSE, R^2
mse = mean_squared_error(y_select_test, y_pred_select)
rmse = root_mean_squared_error(y_test, y_pred_select)

r2 = r2_score(y_select_test, y_pred_select)

print("Unscaled Data Model:")
print(f"Mean Squared Error: {mse:.2f}")
# On average the model fits within two points of predicting
print(f"Root Squared Error: {rmse:.2f}")
print(f"R² Score: {r2:.2f}")

Unscaled Data Model:
Mean Squared Error: 0.68
Root Squared Error: 0.82
R² Score: 0.48

Compared to the full model this model performed slightly worse. It was only able to explain 48% of the variance in the dependent variable compared to 58% in the previous model. Also, on average this model was 0.82 off from predicting the actual median house value for Californian districts which was 0.07 more than the previous model.

In [44]:
print(pd.Series(lin_reg_select.coef_,
                index=X_select.columns))

MedInc       0.542349
AveBedrms    1.170217
AveRooms    -0.246163
dtype: float64

In practice, a simplified model may be preferred to prevent overfitting. I don't believe the previous model was overfitting but if it was selecting only some of the features in the dataset can reduce the problem of overfitting. By doing this, our train accuracy may decrease but our test accuracy would likely increase.